$(function(){
	$("#css-text").tabby();
})


/* Kind of a mess... http://syntaxhighlighter.relic19.net/moreinfo.html */
/* SyntaxHighlight (Modified) */
	/* Src of SWF Clipboard */
	dp.SyntaxHighlighter.ClipboardSwf = 'js/clipboard.swf';

	/* Modified Highlighting */
	function staticallyConvertCode()
	{
		/* The classname of the highlighted code element */
		highlightedClassName = "dp-highlighter";

		/* Code Type (only CSS is Included) */
		classString = "css";

		/* Extract code generated by PHP */
		var originalCode = document.getElementById('code').innerHTML.replace(/&/g,'&amp;').replace(/</g,'&lt;');

		/* Reset the current pre code area */
		document.getElementById('codearea').innerHTML = "<pre name=\"code\" class=\""+classString+"\"></pre>";

		/* Turn Code into Var */
		document.getElementsByName('code')[0].innerHTML = originalCode;

		/* Highlight the code in the <pre> code div. */
		dp.SyntaxHighlighter.HighlightAll('code');

		/* Get the resulting highlighted code element */
		highlightedElement = getCodeElement('\\bdp-highlighter\\b');

		/* Add a hidden textarea containing the original source code to the
		   prettied code so that the menu buttons will work later. */
		highlightedElement.innerHTML += "<textarea style='display:none;' class='originalCode'>"+originalCode+"</textarea>";

		/* Finally, we need to extract the highlighted code html source and write it to the results box */
		document.getElementById('result').value = "<div class=\""+highlightedClassName+"\">" + highlightedElement.innerHTML + "</div>";
	}

	/* Gets a subelement of the codearea node whose classname matched the test parameter */
	function getCodeElement(test)
	{
		node = document.getElementById('codearea');
		var a = [];
		var re = new RegExp(test);
		var els = node.getElementsByTagName("*");
		for(var i=0,j=els.length; i<j; i++)
			if(re.test(els[i].className))
				return els[i];
	}
	
	/* Execute */
	staticallyConvertCode();